# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 217a40c4e3fe0c5a190f5e540928bc15c8d473e33423fbb169ddd8328760cf2cae1a972a787fe3cea7f627028c79883c962f37779599fdeb51ad565d00617eda

test:
  secret_key_base: 168aaf41ca9dfda301ca2bb8be049442259865b6cbc371d837a969c0651b7c3e274132426e37e8a4b22b0c244426953b77be38a84417df245f6b2c80c9ecfcb6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
